"""empty message

Revision ID: 2474c602b719
Revises: 4f556cac532b
Create Date: 2024-01-08 18:12:40.077353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2474c602b719'
down_revision = '4f556cac532b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_addresses_buyer_id_buyers'), 'buyers', ['buyer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_addresses_buyer_id_buyers'), type_='foreignkey')
        batch_op.drop_column('buyer_id')

    # ### end Alembic commands ###
