"""empty message

Revision ID: 2f3311b66b3b
Revises: 814b86b4d670
Create Date: 2024-01-08 17:23:03.817968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3311b66b3b'
down_revision = '814b86b4d670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_products_product_category_id_product_categories'), 'product_categories', ['product_category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_products_product_category_id_product_categories'), type_='foreignkey')
        batch_op.drop_column('product_category_id')

    # ### end Alembic commands ###
