"""empty message

Revision ID: 4f556cac532b
Revises: b1ddc0f418eb
Create Date: 2024-01-08 18:07:11.969599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f556cac532b'
down_revision = 'b1ddc0f418eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_buyers_order_id_orders', type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_buyers_order_id_orders', 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###
