"""empty message

Revision ID: 58d7da86aa98
Revises: d92773cece7f
Create Date: 2024-01-18 20:27:58.913908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d7da86aa98'
down_revision = 'd92773cece7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('business_zip', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('business_zip')
        batch_op.drop_column('business_state')

    # ### end Alembic commands ###
