"""empty message

Revision ID: 64e649636403
Revises: a50ec9c9e00c
Create Date: 2024-01-11 15:57:35.653209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e649636403'
down_revision = 'a50ec9c9e00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_buyers_buyer_email'), ['buyer_email'])
        batch_op.create_unique_constraint(batch_op.f('uq_buyers_buyer_username'), ['buyer_username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_buyers_buyer_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_buyers_buyer_email'), type_='unique')

    # ### end Alembic commands ###
