"""empty message

Revision ID: 814b86b4d670
Revises: 228dc87d478b
Create Date: 2024-01-08 17:18:51.706939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814b86b4d670'
down_revision = '228dc87d478b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sellers_business_id_businesses', type_='foreignkey')
        batch_op.drop_column('business_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_sellers_business_id_businesses', 'businesses', ['business_id'], ['id'])

    # ### end Alembic commands ###
