"""empty message

Revision ID: 8590f1b7d8fd
Revises: 2f3311b66b3b
Create Date: 2024-01-08 17:44:15.109484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8590f1b7d8fd'
down_revision = '2f3311b66b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attribute_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_inventories_attribute_id_attributes'), 'attributes', ['attribute_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inventories_attribute_id_attributes'), type_='foreignkey')
        batch_op.drop_column('attribute_id')

    # ### end Alembic commands ###
