"""empty message

Revision ID: 85a8bcc2b478
Revises: 64e649636403
Create Date: 2024-01-11 19:41:41.568071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a8bcc2b478'
down_revision = '64e649636403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('user_type', sa.Enum('buyer', 'seller', name="user_enum_type"), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], name=op.f('fk_message_recipients_buyer_id_buyers')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_recipients_message_id_messages')),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_message_recipients_seller_id_sellers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_recipients'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('conversations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversations', sa.VARCHAR(), autoincrement=False, nullable=True))

    op.drop_table('message_recipients')
    # ### end Alembic commands ###
