"""empty message

Revision ID: a50ec9c9e00c
Revises: b431fde289a3
Create Date: 2024-01-11 15:36:25.340728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50ec9c9e00c'
down_revision = 'b431fde289a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopify_integrated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_column('shopify_integrated')

    # ### end Alembic commands ###
