"""empty message

Revision ID: a890f04e956f
Revises: 8590f1b7d8fd
Create Date: 2024-01-08 17:52:21.664795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a890f04e956f'
down_revision = '8590f1b7d8fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_buyers_reviews_id_reviews', type_='foreignkey')
        batch_op.drop_column('reviews_id')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('review_img',
               existing_type=postgresql.BYTEA(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('review_img',
               existing_type=postgresql.BYTEA(),
               nullable=False)

    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviews_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_buyers_reviews_id_reviews', 'reviews', ['reviews_id'], ['id'])

    # ### end Alembic commands ###
