"""empty message

Revision ID: b1bdb2b595b1
Revises: c1f0c62f9cd3
Create Date: 2024-01-06 19:47:25.195922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1bdb2b595b1'
down_revision = 'c1f0c62f9cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_businesses_business_name'), ['business_name'])

    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_sellers_seller_email'), ['seller_email'])
        batch_op.create_unique_constraint(batch_op.f('uq_sellers_seller_username'), ['seller_username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_sellers_seller_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_sellers_seller_email'), type_='unique')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_businesses_business_name'), type_='unique')

    # ### end Alembic commands ###
