"""empty message

Revision ID: b1ddc0f418eb
Revises: a890f04e956f
Create Date: 2024-01-08 18:04:17.682941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ddc0f418eb'
down_revision = 'a890f04e956f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_sale_histories_seller_id_sellers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sale_histories_order_id_orders'), 'orders', ['order_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_sale_histories_business_id_businesses'), 'businesses', ['business_id'], ['id'])
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_sale_histories_business_id_businesses'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sale_histories_order_id_orders'), type_='foreignkey')
        batch_op.create_foreign_key('fk_sale_histories_seller_id_sellers', 'sellers', ['seller_id'], ['id'])
        batch_op.drop_column('order_id')
        batch_op.drop_column('business_id')

    # ### end Alembic commands ###
