"""empty message

Revision ID: c1f0c62f9cd3
Revises: 0093639a5aad
Create Date: 2024-01-03 19:44:12.214493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f0c62f9cd3'
down_revision = '0093639a5aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=False))
        batch_op.alter_column('address_line_one',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('postal_code',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('postal_code',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('address_line_one',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
