"""empty message

Revision ID: d92773cece7f
Revises: 85a8bcc2b478
Create Date: 2024-01-14 12:34:36.853481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd92773cece7f'
down_revision = '85a8bcc2b478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_recipients', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=postgresql.ENUM('buyer', 'seller', name='user_enum_type'),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_recipients', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('buyer', 'seller', name='user_enum_type'),
               existing_nullable=True)

    # ### end Alembic commands ###
